name: Build APK

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
    workflow_dispatch: # Позволяет запускать вручную

jobs:
    build-apk:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: |
                  cd flag-quiz
                  npm install

            - name: Build web app
              run: |
                  cd flag-quiz
                  npm run build

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  java-version: "17"
                  distribution: "temurin"

            - name: Setup Android SDK
              uses: android-actions/setup-android@v3

            - name: Copy web assets to Android
              run: |
                  cd flag-quiz
                  npx cap copy

            - name: Build APK
              run: |
                  cd flag-quiz/android
                  ./gradlew assembleDebug

            - name: Upload APK artifact
              uses: actions/upload-artifact@v4
              with:
                  name: flag-quiz-apk
                  path: flag-quiz/android/app/build/outputs/apk/debug/app-debug.apk
                  retention-days: 30

            - name: Create APK in project directory
              run: |
                  mkdir -p flag-quiz/apk-builds
                  cp flag-quiz/android/app/build/outputs/apk/debug/app-debug.apk flag-quiz/apk-builds/flag-quiz-$(date +%Y%m%d-%H%M%S).apk
                  cp flag-quiz/android/app/build/outputs/apk/debug/app-debug.apk flag-quiz/apk-builds/latest.apk

            - name: Upload APK to project directory
              uses: actions/upload-artifact@v4
              with:
                  name: apk-in-project
                  path: flag-quiz/apk-builds/
                  retention-days: 30
