// Скрипт для скачивания флагов стран
import fs from 'fs';
import path from 'path';
import https from 'https';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Создаем директорию для флагов
const flagsDir = path.join(__dirname, '..', 'public', 'flags');
if (!fs.existsSync(flagsDir)) {
  fs.mkdirSync(flagsDir, { recursive: true });
}

// Маппинг кодов стран на URL флагов
const flagUrls = {
  RU: 'https://flagcdn.com/w320/ru.png',
  US: 'https://flagcdn.com/w320/us.png',
  CN: 'https://flagcdn.com/w320/cn.png',
  DE: 'https://flagcdn.com/w320/de.png',
  FR: 'https://flagcdn.com/w320/fr.png',
  GB: 'https://flagcdn.com/w320/gb.png',
  JP: 'https://flagcdn.com/w320/jp.png',
  BR: 'https://flagcdn.com/w320/br.png',
  IN: 'https://flagcdn.com/w320/in.png',
  CA: 'https://flagcdn.com/w320/ca.png',
  AU: 'https://flagcdn.com/w320/au.png',
  IT: 'https://flagcdn.com/w320/it.png',
  ES: 'https://flagcdn.com/w320/es.png',
  KR: 'https://flagcdn.com/w320/kr.png',
  MX: 'https://flagcdn.com/w320/mx.png',
  NL: 'https://flagcdn.com/w320/nl.png',
  SE: 'https://flagcdn.com/w320/se.png',
  NO: 'https://flagcdn.com/w320/no.png',
  CH: 'https://flagcdn.com/w320/ch.png',
  PL: 'https://flagcdn.com/w320/pl.png',
  AR: 'https://flagcdn.com/w320/ar.png',
  ZA: 'https://flagcdn.com/w320/za.png',
  EG: 'https://flagcdn.com/w320/eg.png',
  NG: 'https://flagcdn.com/w320/ng.png',
  TR: 'https://flagcdn.com/w320/tr.png',
  IR: 'https://flagcdn.com/w320/ir.png',
  IQ: 'https://flagcdn.com/w320/iq.png',
  SA: 'https://flagcdn.com/w320/sa.png',
  IL: 'https://flagcdn.com/w320/il.png',
  UA: 'https://flagcdn.com/w320/ua.png',
  BY: 'https://flagcdn.com/w320/by.png',
  KZ: 'https://flagcdn.com/w320/kz.png',
  UZ: 'https://flagcdn.com/w320/uz.png',
  TH: 'https://flagcdn.com/w320/th.png',
  VN: 'https://flagcdn.com/w320/vn.png',
  ID: 'https://flagcdn.com/w320/id.png',
  MY: 'https://flagcdn.com/w320/my.png',
  PH: 'https://flagcdn.com/w320/ph.png',
  BD: 'https://flagcdn.com/w320/bd.png',
  PK: 'https://flagcdn.com/w320/pk.png',
  AF: 'https://flagcdn.com/w320/af.png',
  GR: 'https://flagcdn.com/w320/gr.png',
  PT: 'https://flagcdn.com/w320/pt.png',
  BE: 'https://flagcdn.com/w320/be.png',
  AT: 'https://flagcdn.com/w320/at.png',
  CZ: 'https://flagcdn.com/w320/cz.png',
  HU: 'https://flagcdn.com/w320/hu.png',
  RO: 'https://flagcdn.com/w320/ro.png',
  BG: 'https://flagcdn.com/w320/bg.png',
  HR: 'https://flagcdn.com/w320/hr.png',
  RS: 'https://flagcdn.com/w320/rs.png',
  SI: 'https://flagcdn.com/w320/si.png',
  SK: 'https://flagcdn.com/w320/sk.png',
  EE: 'https://flagcdn.com/w320/ee.png',
  LV: 'https://flagcdn.com/w320/lv.png',
  LT: 'https://flagcdn.com/w320/lt.png',
  FI: 'https://flagcdn.com/w320/fi.png',
  DK: 'https://flagcdn.com/w320/dk.png',
  IS: 'https://flagcdn.com/w320/is.png',
  IE: 'https://flagcdn.com/w320/ie.png',
  LU: 'https://flagcdn.com/w320/lu.png',
  MT: 'https://flagcdn.com/w320/mt.png',
  CY: 'https://flagcdn.com/w320/cy.png',
  AL: 'https://flagcdn.com/w320/al.png',
  MK: 'https://flagcdn.com/w320/mk.png',
  ME: 'https://flagcdn.com/w320/me.png',
  BA: 'https://flagcdn.com/w320/ba.png',
  MD: 'https://flagcdn.com/w320/md.png',
  GE: 'https://flagcdn.com/w320/ge.png',
  AM: 'https://flagcdn.com/w320/am.png',
  AZ: 'https://flagcdn.com/w320/az.png',
  KG: 'https://flagcdn.com/w320/kg.png',
  TJ: 'https://flagcdn.com/w320/tj.png',
  TM: 'https://flagcdn.com/w320/tm.png',
  MN: 'https://flagcdn.com/w320/mn.png',
  KP: 'https://flagcdn.com/w320/kp.png',
  TW: 'https://flagcdn.com/w320/tw.png',
  HK: 'https://flagcdn.com/w320/hk.png',
  SG: 'https://flagcdn.com/w320/sg.png',
  LK: 'https://flagcdn.com/w320/lk.png',
  NP: 'https://flagcdn.com/w320/np.png',
  BT: 'https://flagcdn.com/w320/bt.png',
  MM: 'https://flagcdn.com/w320/mm.png',
  LA: 'https://flagcdn.com/w320/la.png',
  KH: 'https://flagcdn.com/w320/kh.png',
  BN: 'https://flagcdn.com/w320/bn.png',
  TL: 'https://flagcdn.com/w320/tl.png',
  PG: 'https://flagcdn.com/w320/pg.png',
  FJ: 'https://flagcdn.com/w320/fj.png',
  NZ: 'https://flagcdn.com/w320/nz.png',
  CL: 'https://flagcdn.com/w320/cl.png',
  PE: 'https://flagcdn.com/w320/pe.png',
  CO: 'https://flagcdn.com/w320/co.png',
  VE: 'https://flagcdn.com/w320/ve.png',
  EC: 'https://flagcdn.com/w320/ec.png',
  BO: 'https://flagcdn.com/w320/bo.png',
  PY: 'https://flagcdn.com/w320/py.png',
  UY: 'https://flagcdn.com/w320/uy.png',
  GY: 'https://flagcdn.com/w320/gy.png',
  SR: 'https://flagcdn.com/w320/sr.png',
  GF: 'https://flagcdn.com/w320/gf.png',
  CU: 'https://flagcdn.com/w320/cu.png',
  JM: 'https://flagcdn.com/w320/jm.png',
  HT: 'https://flagcdn.com/w320/ht.png',
  DO: 'https://flagcdn.com/w320/do.png',
  PR: 'https://flagcdn.com/w320/pr.png',
  TT: 'https://flagcdn.com/w320/tt.png',
  BB: 'https://flagcdn.com/w320/bb.png',
  LC: 'https://flagcdn.com/w320/lc.png',
  GD: 'https://flagcdn.com/w320/gd.png',
  VC: 'https://flagcdn.com/w320/vc.png',
  AG: 'https://flagcdn.com/w320/ag.png',
  DM: 'https://flagcdn.com/w320/dm.png',
  KN: 'https://flagcdn.com/w320/kn.png',
  BZ: 'https://flagcdn.com/w320/bz.png',
  GT: 'https://flagcdn.com/w320/gt.png',
  HN: 'https://flagcdn.com/w320/hn.png',
  SV: 'https://flagcdn.com/w320/sv.png',
  NI: 'https://flagcdn.com/w320/ni.png',
  CR: 'https://flagcdn.com/w320/cr.png',
  PA: 'https://flagcdn.com/w320/pa.png',
  DZ: 'https://flagcdn.com/w320/dz.png',
  AO: 'https://flagcdn.com/w320/ao.png',
  BJ: 'https://flagcdn.com/w320/bj.png',
  BW: 'https://flagcdn.com/w320/bw.png',
  BF: 'https://flagcdn.com/w320/bf.png',
  BI: 'https://flagcdn.com/w320/bi.png',
  CM: 'https://flagcdn.com/w320/cm.png',
  CV: 'https://flagcdn.com/w320/cv.png',
  CF: 'https://flagcdn.com/w320/cf.png',
  TD: 'https://flagcdn.com/w320/td.png',
  KM: 'https://flagcdn.com/w320/km.png',
  CG: 'https://flagcdn.com/w320/cg.png',
  CD: 'https://flagcdn.com/w320/cd.png',
  DJ: 'https://flagcdn.com/w320/dj.png',
  GQ: 'https://flagcdn.com/w320/gq.png',
  ER: 'https://flagcdn.com/w320/er.png',
  SZ: 'https://flagcdn.com/w320/sz.png',
  ET: 'https://flagcdn.com/w320/et.png',
  GA: 'https://flagcdn.com/w320/ga.png',
  GM: 'https://flagcdn.com/w320/gm.png',
  GH: 'https://flagcdn.com/w320/gh.png',
  GN: 'https://flagcdn.com/w320/gn.png',
  GW: 'https://flagcdn.com/w320/gw.png',
  CI: 'https://flagcdn.com/w320/ci.png',
  KE: 'https://flagcdn.com/w320/ke.png',
  LS: 'https://flagcdn.com/w320/ls.png',
  LR: 'https://flagcdn.com/w320/lr.png',
  LY: 'https://flagcdn.com/w320/ly.png',
  MG: 'https://flagcdn.com/w320/mg.png',
  MW: 'https://flagcdn.com/w320/mw.png',
  ML: 'https://flagcdn.com/w320/ml.png',
  MR: 'https://flagcdn.com/w320/mr.png',
  MU: 'https://flagcdn.com/w320/mu.png',
  MA: 'https://flagcdn.com/w320/ma.png',
  MZ: 'https://flagcdn.com/w320/mz.png',
  NA: 'https://flagcdn.com/w320/na.png',
  NE: 'https://flagcdn.com/w320/ne.png',
  RW: 'https://flagcdn.com/w320/rw.png',
  ST: 'https://flagcdn.com/w320/st.png',
  SN: 'https://flagcdn.com/w320/sn.png',
  SC: 'https://flagcdn.com/w320/sc.png',
  SL: 'https://flagcdn.com/w320/sl.png',
  SO: 'https://flagcdn.com/w320/so.png',
  SS: 'https://flagcdn.com/w320/ss.png',
  SD: 'https://flagcdn.com/w320/sd.png',
  TZ: 'https://flagcdn.com/w320/tz.png',
  TG: 'https://flagcdn.com/w320/tg.png',
  TN: 'https://flagcdn.com/w320/tn.png',
  UG: 'https://flagcdn.com/w320/ug.png',
  ZM: 'https://flagcdn.com/w320/zm.png',
  ZW: 'https://flagcdn.com/w320/zw.png',
  AE: 'https://flagcdn.com/w320/ae.png',
  QA: 'https://flagcdn.com/w320/qa.png',
  KW: 'https://flagcdn.com/w320/kw.png',
  JO: 'https://flagcdn.com/w320/jo.png',
  LB: 'https://flagcdn.com/w320/lb.png',
  SY: 'https://flagcdn.com/w320/sy.png',
  YE: 'https://flagcdn.com/w320/ye.png',
  OM: 'https://flagcdn.com/w320/om.png',
  BH: 'https://flagcdn.com/w320/bh.png',
  PW: 'https://flagcdn.com/w320/pw.png',
  TV: 'https://flagcdn.com/w320/tv.png',
  MV: 'https://flagcdn.com/w320/mv.png',
  TO: 'https://flagcdn.com/w320/to.png',
  WS: 'https://flagcdn.com/w320/ws.png',
  SB: 'https://flagcdn.com/w320/sb.png',
  LI: 'https://flagcdn.com/w320/li.png',
  BS: 'https://flagcdn.com/w320/bs.png',
  VU: 'https://flagcdn.com/w320/vu.png',
  KI: 'https://flagcdn.com/w320/ki.png',
  MC: 'https://flagcdn.com/w320/mc.png',
  SM: 'https://flagcdn.com/w320/sm.png',
  NR: 'https://flagcdn.com/w320/nr.png',
  FM: 'https://flagcdn.com/w320/fm.png',
  MH: 'https://flagcdn.com/w320/mh.png',
  AD: 'https://flagcdn.com/w320/ad.png',
};

// Функция для скачивания файла
function downloadFile(url, filepath) {
  return new Promise((resolve, reject) => {
    const file = fs.createWriteStream(filepath);

    https
      .get(url, (response) => {
        if (response.statusCode !== 200) {
          reject(new Error(`HTTP ${response.statusCode}: ${response.statusMessage}`));
          return;
        }

        response.pipe(file);

        file.on('finish', () => {
          file.close();
          resolve();
        });

        file.on('error', (err) => {
          fs.unlink(filepath, () => {}); // Удаляем частично скачанный файл
          reject(err);
        });
      })
      .on('error', reject);
  });
}

// Функция для скачивания всех флагов
async function downloadAllFlags() {
  console.log('Начинаем скачивание флагов...');

  const countries = [
    { code: 'RU', name: 'russia.png' },
    { code: 'US', name: 'usa.png' },
    { code: 'CN', name: 'china.png' },
    { code: 'DE', name: 'germany.png' },
    { code: 'FR', name: 'france.png' },
    { code: 'GB', name: 'uk.png' },
    { code: 'JP', name: 'japan.png' },
    { code: 'BR', name: 'brazil.png' },
    { code: 'IN', name: 'india.png' },
    { code: 'CA', name: 'canada.png' },
    { code: 'AU', name: 'australia.png' },
    { code: 'IT', name: 'italy.png' },
    { code: 'ES', name: 'spain.png' },
    { code: 'KR', name: 'south-korea.png' },
    { code: 'MX', name: 'mexico.png' },
    { code: 'NL', name: 'netherlands.png' },
    { code: 'SE', name: 'sweden.png' },
    { code: 'NO', name: 'norway.png' },
    { code: 'CH', name: 'switzerland.png' },
    { code: 'PL', name: 'poland.png' },
    { code: 'AR', name: 'argentina.png' },
    { code: 'ZA', name: 'south-africa.png' },
    { code: 'EG', name: 'egypt.png' },
    { code: 'NG', name: 'nigeria.png' },
    { code: 'TR', name: 'turkey.png' },
    { code: 'IR', name: 'iran.png' },
    { code: 'IQ', name: 'iraq.png' },
    { code: 'SA', name: 'saudi-arabia.png' },
    { code: 'IL', name: 'israel.png' },
    { code: 'UA', name: 'ukraine.png' },
    { code: 'BY', name: 'belarus.png' },
    { code: 'KZ', name: 'kazakhstan.png' },
    { code: 'UZ', name: 'uzbekistan.png' },
    { code: 'TH', name: 'thailand.png' },
    { code: 'VN', name: 'vietnam.png' },
    { code: 'ID', name: 'indonesia.png' },
    { code: 'MY', name: 'malaysia.png' },
    { code: 'PH', name: 'philippines.png' },
    { code: 'BD', name: 'bangladesh.png' },
    { code: 'PK', name: 'pakistan.png' },
    { code: 'AF', name: 'afghanistan.png' },
    { code: 'GR', name: 'greece.png' },
    { code: 'PT', name: 'portugal.png' },
    { code: 'BE', name: 'belgium.png' },
    { code: 'AT', name: 'austria.png' },
    { code: 'CZ', name: 'czech-republic.png' },
    { code: 'HU', name: 'hungary.png' },
    { code: 'RO', name: 'romania.png' },
    { code: 'BG', name: 'bulgaria.png' },
    { code: 'HR', name: 'croatia.png' },
    { code: 'RS', name: 'serbia.png' },
    { code: 'SI', name: 'slovenia.png' },
    { code: 'SK', name: 'slovakia.png' },
    { code: 'EE', name: 'estonia.png' },
    { code: 'LV', name: 'latvia.png' },
    { code: 'LT', name: 'lithuania.png' },
    { code: 'FI', name: 'finland.png' },
    { code: 'DK', name: 'denmark.png' },
    { code: 'IS', name: 'iceland.png' },
    { code: 'IE', name: 'ireland.png' },
    { code: 'LU', name: 'luxembourg.png' },
    { code: 'MT', name: 'malta.png' },
    { code: 'CY', name: 'cyprus.png' },
    { code: 'AL', name: 'albania.png' },
    { code: 'MK', name: 'north-macedonia.png' },
    { code: 'ME', name: 'montenegro.png' },
    { code: 'BA', name: 'bosnia-herzegovina.png' },
    { code: 'MD', name: 'moldova.png' },
    { code: 'GE', name: 'georgia.png' },
    { code: 'AM', name: 'armenia.png' },
    { code: 'AZ', name: 'azerbaijan.png' },
    { code: 'KG', name: 'kyrgyzstan.png' },
    { code: 'TJ', name: 'tajikistan.png' },
    { code: 'TM', name: 'turkmenistan.png' },
    { code: 'MN', name: 'mongolia.png' },
    { code: 'KP', name: 'north-korea.png' },
    { code: 'TW', name: 'taiwan.png' },
    { code: 'HK', name: 'hong-kong.png' },
    { code: 'SG', name: 'singapore.png' },
    { code: 'LK', name: 'sri-lanka.png' },
    { code: 'NP', name: 'nepal.png' },
    { code: 'BT', name: 'bhutan.png' },
    { code: 'MM', name: 'myanmar.png' },
    { code: 'LA', name: 'laos.png' },
    { code: 'KH', name: 'cambodia.png' },
    { code: 'BN', name: 'brunei.png' },
    { code: 'TL', name: 'east-timor.png' },
    { code: 'PG', name: 'papua-new-guinea.png' },
    { code: 'FJ', name: 'fiji.png' },
    { code: 'NZ', name: 'new-zealand.png' },
    { code: 'CL', name: 'chile.png' },
    { code: 'PE', name: 'peru.png' },
    { code: 'CO', name: 'colombia.png' },
    { code: 'VE', name: 'venezuela.png' },
    { code: 'EC', name: 'ecuador.png' },
    { code: 'BO', name: 'bolivia.png' },
    { code: 'PY', name: 'paraguay.png' },
    { code: 'UY', name: 'uruguay.png' },
    { code: 'GY', name: 'guyana.png' },
    { code: 'SR', name: 'suriname.png' },
    { code: 'GF', name: 'french-guiana.png' },
    { code: 'CU', name: 'cuba.png' },
    { code: 'JM', name: 'jamaica.png' },
    { code: 'HT', name: 'haiti.png' },
    { code: 'DO', name: 'dominican-republic.png' },
    { code: 'PR', name: 'puerto-rico.png' },
    { code: 'TT', name: 'trinidad-tobago.png' },
    { code: 'BB', name: 'barbados.png' },
    { code: 'LC', name: 'saint-lucia.png' },
    { code: 'GD', name: 'grenada.png' },
    { code: 'VC', name: 'saint-vincent-grenadines.png' },
    { code: 'AG', name: 'antigua-barbuda.png' },
    { code: 'DM', name: 'dominica.png' },
    { code: 'KN', name: 'saint-kitts-nevis.png' },
    { code: 'BZ', name: 'belize.png' },
    { code: 'GT', name: 'guatemala.png' },
    { code: 'HN', name: 'honduras.png' },
    { code: 'SV', name: 'el-salvador.png' },
    { code: 'NI', name: 'nicaragua.png' },
    { code: 'CR', name: 'costa-rica.png' },
    { code: 'PA', name: 'panama.png' },
    { code: 'DZ', name: 'algeria.png' },
    { code: 'AO', name: 'angola.png' },
    { code: 'BJ', name: 'benin.png' },
    { code: 'BW', name: 'botswana.png' },
    { code: 'BF', name: 'burkina-faso.png' },
    { code: 'BI', name: 'burundi.png' },
    { code: 'CM', name: 'cameroon.png' },
    { code: 'CV', name: 'cape-verde.png' },
    { code: 'CF', name: 'central-african-republic.png' },
    { code: 'TD', name: 'chad.png' },
    { code: 'KM', name: 'comoros.png' },
    { code: 'CG', name: 'congo.png' },
    { code: 'CD', name: 'democratic-republic-congo.png' },
    { code: 'DJ', name: 'djibouti.png' },
    { code: 'GQ', name: 'equatorial-guinea.png' },
    { code: 'ER', name: 'eritrea.png' },
    { code: 'SZ', name: 'eswatini.png' },
    { code: 'ET', name: 'ethiopia.png' },
    { code: 'GA', name: 'gabon.png' },
    { code: 'GM', name: 'gambia.png' },
    { code: 'GH', name: 'ghana.png' },
    { code: 'GN', name: 'guinea.png' },
    { code: 'GW', name: 'guinea-bissau.png' },
    { code: 'CI', name: 'ivory-coast.png' },
    { code: 'KE', name: 'kenya.png' },
    { code: 'LS', name: 'lesotho.png' },
    { code: 'LR', name: 'liberia.png' },
    { code: 'LY', name: 'libya.png' },
    { code: 'MG', name: 'madagascar.png' },
    { code: 'MW', name: 'malawi.png' },
    { code: 'ML', name: 'mali.png' },
    { code: 'MR', name: 'mauritania.png' },
    { code: 'MU', name: 'mauritius.png' },
    { code: 'MA', name: 'morocco.png' },
    { code: 'MZ', name: 'mozambique.png' },
    { code: 'NA', name: 'namibia.png' },
    { code: 'NE', name: 'niger.png' },
    { code: 'RW', name: 'rwanda.png' },
    { code: 'ST', name: 'sao-tome-principe.png' },
    { code: 'SN', name: 'senegal.png' },
    { code: 'SC', name: 'seychelles.png' },
    { code: 'SL', name: 'sierra-leone.png' },
    { code: 'SO', name: 'somalia.png' },
    { code: 'SS', name: 'south-sudan.png' },
    { code: 'SD', name: 'sudan.png' },
    { code: 'TZ', name: 'tanzania.png' },
    { code: 'TG', name: 'togo.png' },
    { code: 'TN', name: 'tunisia.png' },
    { code: 'UG', name: 'uganda.png' },
    { code: 'ZM', name: 'zambia.png' },
    { code: 'ZW', name: 'zimbabwe.png' },
    { code: 'AE', name: 'uae.png' },
    { code: 'QA', name: 'qatar.png' },
    { code: 'KW', name: 'kuwait.png' },
    { code: 'JO', name: 'jordan.png' },
    { code: 'LB', name: 'lebanon.png' },
    { code: 'SY', name: 'syria.png' },
    { code: 'YE', name: 'yemen.png' },
    { code: 'OM', name: 'oman.png' },
    { code: 'BH', name: 'bahrain.png' },
    { code: 'PW', name: 'palau.png' },
    { code: 'TV', name: 'tuvalu.png' },
    { code: 'MV', name: 'maldives.png' },
    { code: 'TO', name: 'tonga.png' },
    { code: 'WS', name: 'samoa.png' },
    { code: 'SB', name: 'solomon-islands.png' },
    { code: 'LI', name: 'liechtenstein.png' },
    { code: 'BS', name: 'bahamas.png' },
    { code: 'VU', name: 'vanuatu.png' },
    { code: 'KI', name: 'kiribati.png' },
    { code: 'MC', name: 'monaco.png' },
    { code: 'SM', name: 'san-marino.png' },
    { code: 'NR', name: 'nauru.png' },
    { code: 'FM', name: 'micronesia.png' },
    { code: 'MH', name: 'marshall-islands.png' },
    { code: 'AD', name: 'andorra.png' },
  ];

  let successCount = 0;
  let errorCount = 0;

  for (const country of countries) {
    try {
      const url = flagUrls[country.code];
      if (!url) {
        console.log(`❌ URL не найден для ${country.name} (${country.code})`);
        errorCount++;
        continue;
      }

      const filepath = path.join(flagsDir, country.name);

      // Проверяем, существует ли уже файл
      if (fs.existsSync(filepath)) {
        console.log(`⏭️  Пропускаем ${country.name} (уже существует)`);
        continue;
      }

      console.log(`⬇️  Скачиваем ${country.name}...`);
      await downloadFile(url, filepath);
      console.log(`✅ Скачан ${country.name}`);
      successCount++;

      // Небольшая пауза между запросами
      await new Promise((resolve) => setTimeout(resolve, 100));
    } catch (error) {
      console.error(`❌ Ошибка при скачивании ${country.name}:`, error.message);
      errorCount++;
    }
  }

  console.log(`\n📊 Результат скачивания:`);
  console.log(`✅ Успешно: ${successCount}`);
  console.log(`❌ Ошибок: ${errorCount}`);
  console.log(`📁 Флаги сохранены в: ${flagsDir}`);
}

// Запускаем скачивание
downloadAllFlags().catch(console.error);
