name: Build APK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build web app
        run: npm run build

      - name: Verify build output
        run: |
          ls -la dist/
          echo "Build completed, dist folder contents:"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Add Capacitor Android plugin
        run: npx cap add android

      - name: Copy web assets to Android
        run: npx cap copy

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: flag-quiz-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Create APK in project directory
        run: |
          mkdir -p apk-builds
          cp android/app/build/outputs/apk/debug/app-debug.apk apk-builds/flag-quiz-$(date +%Y%m%d-%H%M%S).apk
          cp android/app/build/outputs/apk/debug/app-debug.apk apk-builds/latest.apk

      - name: Upload APK to project directory
        uses: actions/upload-artifact@v4
        with:
          name: apk-in-project
          path: apk-builds/
          retention-days: 30
