name: Build APK (clean android)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install npm dependencies (clean)
        run: |
          npm ci

      - name: Ensure Capacitor CLI is present
        run: |
          npm install --no-audit --no-fund @capacitor/cli@latest

      - name: Build web app
        run: |
          npm run build

      - name: Verify build output
        run: |
          echo "dist content:"
          ls -la dist || true

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        # If you need explicit SDK/build-tools, enable and adjust the block below:
        # with:
        #   api-level: 33
        #   build-tools: "33.0.2"

      - name: Remove android directory (destructive)
        run: |
          if [ -d android ]; then
            echo "Removing existing android directory for a clean add (destructive)"
            rm -rf android
          else
            echo "No android directory found — continuing"
          fi

      - name: Ensure @capacitor/android package present
        run: |
          npm install --no-audit --no-fund @capacitor/android@latest

      - name: Add Capacitor Android (clean add)
        run: |
          npx cap add android

      - name: show android/settings.gradle
        run: |
          echo "---- android/settings.gradle ----"
          sed -n '1,200p' android/settings.gradle || true
          echo "---- end settings.gradle ----"

      - name: Sync / Copy web assets to Android
        run: |
          npx cap sync android
          npx cap copy android

      - name: Make gradlew executable
        run: |
          chmod +x android/gradlew
          ls -la android || true

      - name: Build APK (assembleDebug)
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK artifact (flag-quiz-apk)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flag-quiz-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Create APK in project directory
        if: always()
        run: |
          mkdir -p apk-builds
          if [ -f android/app/build/outputs/apk/debug/app-debug.apk ]; then
            cp android/app/build/outputs/apk/debug/app-debug.apk apk-builds/flag-quiz-$(date +%Y%m%d-%H%M%S).apk
            cp android/app/build/outputs/apk/debug/app-debug.apk apk-builds/latest.apk
          else
            echo "APK not found, skipping copying to apk-builds"
          fi

      - name: Upload APK to project directory
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apk-in-project
          path: apk-builds/
          retention-days: 30
